[2015-10-01 16:31:34.664] [ERROR] client-error - ReferenceError: domain is not defined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:69:41
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:153:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:31:57.755] [ERROR] client-error - ReferenceError: domain is not defined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:69:41
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:153:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:32:12.176] [ERROR] client-error - ReferenceError: domain is not defined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:69:41
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:153:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:32:29.509] [ERROR] client-error - ReferenceError: domain is not defined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:69:41
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:153:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:37:49.205] [ERROR] client-error - TypeError: Cannot read property 'statuses' of null
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:155:28
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:305:14)
    at ClientRequest.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:397:7)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1455:17)
    at Socket.emit (events.js:117:20)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:38:55.516] [ERROR] client-error - TypeError: Cannot read property 'statuses' of null
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:152:28
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:305:14)
    at ClientRequest.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:397:7)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1455:17)
    at Socket.emit (events.js:117:20)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
[2015-10-01 16:40:16.364] [ERROR] client-error - [SyntaxError: Unexpected token }]
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:281:17
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:322:21)
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:226:35)
    at Object.client.requireWorkers (D:\Node\MY MODULES\kazi2\client\lib\client.js:274:9)
    at EventEmitter.<anonymous> (D:\Node\MY MODULES\kazi2\client\lib\client.js:253:13)
    at EventEmitter.emit (events.js:98:17)
    at EventEmitter.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\chokidar\index.js:136:15)
    at EventEmitter.FSWatcher._emit (D:\Node\MY MODULES\kazi2\client\node_modules\chokidar\index.js:152:5)
[2015-10-01 20:33:29.621] [ERROR] client-error - [[94m[1m[4m   JEFFREY    [24m[22m[39m] >> Error: read ECONNRESET
[2015-10-02 03:13:12.902] [ERROR] client-error - [SyntaxError: Unexpected token +]
SyntaxError: Unexpected token +
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:281:17
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:322:21)
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:333:15
[2015-10-02 03:13:50.871] [ERROR] client-error - [SyntaxError: Unexpected token }]
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:281:17
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:322:21)
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:333:15
[2015-10-02 03:15:49.825] [ERROR] client-error - [SyntaxError: Unexpected token }]
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:281:17
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:322:21)
    at D:\Node\MY MODULES\kazi2\client\node_modules\async\lib\async.js:333:15
[2015-10-02 03:23:11.229] [ERROR] client-error - [SyntaxError: Unexpected token .]
SyntaxError: Unexpected token .
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:1:71)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[2015-10-02 03:27:24.004] [ERROR] client-error - ReferenceError: jobs is not defined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:85:17
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:154:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 03:37:12.549] [ERROR] client-error - [[94m[1m[4m   CAROLINE   [24m[22m[39m] >> Error: read ECONNRESET
[2015-10-02 03:37:56.455] [ERROR] client-error - [[94m[1m[4m   ZACHARY    [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 03:40:37.657] [ERROR] client-error - [[94m[1m[4m     IDA      [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 03:58:03.554] [ERROR] client-error - [[94m[1m[4m    CALEB     [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 04:00:35.895] [ERROR] client-error - [[94m[1m[4m   MILDRED    [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 04:18:43.797] [ERROR] client-error - [[94m[1m[4m   FRANKLIN   [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 04:22:01.530] [ERROR] client-error - [[94m[1m[4m    LUCILE    [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 04:23:04.554] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 04:23:18.911] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 04:23:33.292] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 04:23:47.734] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 04:24:02.272] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 04:24:16.804] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:124:22)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
