[2015-10-02 05:06:23.774] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:06:39.740] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:06:56.077] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:07:12.306] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:07:30.665] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:07:41.491] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:07:53.875] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:08:13.767] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:149:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:141:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:09:05.909] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:152:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:144:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:09:42.668] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:152:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:144:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:10:03.374] [ERROR] client-error - TypeError: Cannot call method 'join' of undefined
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:152:56
    at D:\Node\node_modules\async\lib\async.js:187:20
    at replenish (D:\Node\node_modules\async\lib\async.js:322:21)
    at D:\Node\node_modules\async\lib\async.js:333:15
    at Object.async.forEachLimit.async.eachLimit (D:\Node\node_modules\async\lib\async.js:226:35)
    at track (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:144:8)
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:26:4)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
[2015-10-02 05:10:32.733] [ERROR] client-error - TypeError: Object  has no method '_union'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:179:15
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:187:5
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:52:16
    at replenish (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:317:29)
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:329:29
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\async\lib\async.js:44:16
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:152:6
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\index.js:216:6
    at respond (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:275:9)
    at checkRespForFailure (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\transport.js:219:7)
    at HttpConnector.<anonymous> (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\BRIDGE\node_modules\elasticsearch\src\lib\connectors\http.js:155:7)
    at IncomingMessage.wrapper (D:\Node\MY MODULES\WORKERS\tracking\twitter\node_modules\lodash\index.js:3095:19)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:21:52.326] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:22:29.325] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:23:05.693] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:23:41.490] [ERROR] client-error - [[94m[1m[4m   JEREMIAH   [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 05:23:57.251] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:24:35.146] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:25:12.867] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:25:38.631] [ERROR] client-error - [[94m[1m[4m   ZACHARY    [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 05:25:52.110] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:26:27.926] [ERROR] client-error - TypeError: Object #<Object> has no method 'log'
    at D:\Node\MY MODULES\WORKERS\tracking\twitter\track.js:191:14
    at responseHandler (D:\Node\node_modules\twit\lib\oarequest.js:377:12)
    at passBackControl (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:367:11)
    at IncomingMessage.<anonymous> (D:\Node\node_modules\twit\node_modules\oauth\lib\oauth.js:386:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:32:38.933] [ERROR] client-error - [[94m[1m[4m     DEAN     [24m[22m[39m] >> Error: connect ECONNREFUSED
[2015-10-02 05:49:19.324] [ERROR] client-error - ReferenceError: domain is not defined
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\es\bulk.js:15:14)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[2015-10-02 05:49:25.886] [ERROR] client-error - ReferenceError: domain is not defined
    at Object.worker.run (D:\Node\MY MODULES\WORKERS\es\bulk.js:15:14)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:130:32
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at D:\Node\MY MODULES\kazi2\client\lib\client.js:124:20
    at Request._callback (D:\Node\MY MODULES\kazi2\client\lib\client.js:364:5)
    at Request.self.callback (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Node\MY MODULES\kazi2\client\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
